spring.application.name=BootMVCProj09-CRUD-EmployeeManagementSystem
server.port=7777
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=KVSRM
spring.datasource.password=KVSRM

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true